// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ5LmNVUUPdTfBKkmckvY1kAAUaF_LbFQ',
    appId: '1:211937448030:web:dfe25e3139459787aaa4cf',
    messagingSenderId: '211937448030',
    projectId: 'transmaa-driver',
    authDomain: 'transmaa-driver.firebaseapp.com',
    storageBucket: 'transmaa-driver.appspot.com',
    measurementId: 'G-VBJ6Z2T4R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ppiULMPyCH2cvl2g7TXzc9jngjt92VA',
    appId: '1:211937448030:android:3e7602415190829caaa4cf',
    messagingSenderId: '211937448030',
    projectId: 'transmaa-driver',
    storageBucket: 'transmaa-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGDz8vUYFqYY1kRZRkXH7GAObmbvVzRrI',
    appId: '1:211937448030:ios:d429f8c446affd36aaa4cf',
    messagingSenderId: '211937448030',
    projectId: 'transmaa-driver',
    storageBucket: 'transmaa-driver.appspot.com',
    iosBundleId: 'com.example.transmaacode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGDz8vUYFqYY1kRZRkXH7GAObmbvVzRrI',
    appId: '1:211937448030:ios:b118a708276ae09eaaa4cf',
    messagingSenderId: '211937448030',
    projectId: 'transmaa-driver',
    storageBucket: 'transmaa-driver.appspot.com',
    iosBundleId: 'com.example.transmaacode.RunnerTests',
  );
}
